# Discovery fuentes Kaggle

In [1]:
import pandas as pd
df = pd.read_csv('data\marketing_campaign_dataset.csv')

<>:2: SyntaxWarning: invalid escape sequence '\m'
<>:2: SyntaxWarning: invalid escape sequence '\m'
C:\Users\GIGABYTE\AppData\Local\Temp\ipykernel_25336\1189155681.py:2: SyntaxWarning: invalid escape sequence '\m'
  df = pd.read_csv('data\marketing_campaign_dataset.csv')

In [2]:
df.shape

(200000, 16)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200000 non-null  int64
 1   Company           200000 non-null  str
 2   Campaign_Type     200000 non-null  str
 3   Target_Audience   200000 non-null  str
 4   Duration          200000 non-null  str
 5   Channel_Used      200000 non-null  str
 6   Conversion_Rate   200000 non-null  float64
 7   Acquisition_Cost  200000 non-null  str
 8   ROI               200000 non-null  float64
 9   Location          200000 non-null  str
 10  Language          200000 non-null  str
 11  Clicks            200000 non-null  int64
 12  Impressions       200000 non-null  int64
 13  Engagement_Score  200000 non-null  int64
 14  Customer_Segment  200000 non-null  str
 15  Date              200000 non-null  str
dtypes: float64(2), int64(4), str(10)
memory usage: 24.4 MB

- Channel_Used : Plataforma de Marketing
- Sin Campaign_Id

In [5]:
df.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"$16,174.00",6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"$11,566.00",5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,"$10,200.00",7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,"$12,724.00",5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,"$16,452.00",6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05

In [6]:
df.Company.unique()

<StringArray>
['Innovate Industries',      'NexGen Systems',   'Alpha Innovations',
  'DataTech Solutions',            'TechCorp']
Length: 5, dtype: str

In [8]:
df[['Company', 'Campaign_Type', 'Target_Audience', 'Channel_Used', 'Location', 'Language', 'Customer_Segment']]

,Company,Campaign_Type,Target_Audience,Channel_Used,Location,Language,Customer_Segment
0,Innovate Industries,Email,Men 18-24,Google Ads,Chicago,Spanish,Health & Wellness
1,NexGen Systems,Email,Women 35-44,Google Ads,New York,German,Fashionistas
2,Alpha Innovations,Influencer,Men 25-34,YouTube,Los Angeles,French,Outdoor Adventurers
3,DataTech Solutions,Display,All Ages,YouTube,Miami,Mandarin,Health & Wellness
4,NexGen Systems,Email,Men 25-34,YouTube,Los Angeles,Mandarin,Health & Wellness
...,...,...,...,...,...,...,...
199995,TechCorp,Display,All Ages,Google Ads,Chicago,German,Tech Enthusiasts
199996,DataTech Solutions,Email,Men 25-34,Facebook,Chicago,Spanish,Foodies
199997,DataTech Solutions,Social Media,Men 18-24,Website,New York,Mandarin,Tech Enthusiasts
199998,Innovate Industries,Influencer,All Ages,YouTube,Houston,French,Foodies
199999,Innovate Industries,Social Media,Women 35-44,Google Ads,Chicago,Spanish,Tech Enthusiasts

In [9]:
df[['Company', 'Campaign_Type', 'Target_Audience', 'Channel_Used', 'Location', 'Language', 'Customer_Segment']].drop_duplicates()

,Company,Campaign_Type,Target_Audience,Channel_Used,Location,Language,Customer_Segment
0,Innovate Industries,Email,Men 18-24,Google Ads,Chicago,Spanish,Health & Wellness
1,NexGen Systems,Email,Women 35-44,Google Ads,New York,German,Fashionistas
2,Alpha Innovations,Influencer,Men 25-34,YouTube,Los Angeles,French,Outdoor Adventurers
3,DataTech Solutions,Display,All Ages,YouTube,Miami,Mandarin,Health & Wellness
4,NexGen Systems,Email,Men 25-34,YouTube,Los Angeles,Mandarin,Health & Wellness
...,...,...,...,...,...,...,...
199972,Alpha Innovations,Search,Women 25-34,Instagram,Houston,Spanish,Fashionistas
199980,DataTech Solutions,Email,Women 25-34,YouTube,Miami,English,Tech Enthusiasts
199987,TechCorp,Display,Men 18-24,Website,New York,German,Tech Enthusiasts
199993,DataTech Solutions,Influencer,Women 35-44,Facebook,Chicago,Mandarin,Fashionistas
199998,Innovate Industries,Influencer,All Ages,YouTube,Houston,French,Foodies

In [10]:
df.Channel_Used.unique()

<StringArray>
['Google Ads', 'YouTube', 'Instagram', 'Website', 'Facebook', 'Email']
Length: 6, dtype: str

In [13]:
df[['Channel_Used', 'Campaign_Type']].drop_duplicates().sort_values(by='Channel_Used')

    Channel_Used Campaign_Type
29         Email  Social Media
28         Email    Influencer
10         Email       Display
20         Email        Search
57         Email         Email
50      Facebook        Search
48      Facebook       Display
23      Facebook         Email
8       Facebook  Social Media
21      Facebook    Influencer
0     Google Ads         Email
45    Google Ads       Display
18    Google Ads  Social Media
11    Google Ads    Influencer
7     Google Ads        Search
17     Instagram    Influencer
9      Instagram         Email
25     Instagram        Search
47     Instagram  Social Media
5      Instagram       Display
51       Website        Search
40       Website  Social Media
6        Website         Email
14       Website       Display
102      Website    Influencer
4        YouTube         Email
46       YouTube        Search
3        YouTube       Display
2        YouTube    Influencer
15       YouTube  Social Media

In [18]:
df[['Company', 'Campaign_Type', 'Language', 'Customer_Segment']].drop_duplicates().sort_values(by='Company')

               Company Campaign_Type  Language     Customer_Segment
452  Alpha Innovations    Influencer    French     Tech Enthusiasts
674  Alpha Innovations    Influencer   English    Health & Wellness
668  Alpha Innovations    Influencer   Spanish              Foodies
136  Alpha Innovations  Social Media   Spanish         Fashionistas
634  Alpha Innovations        Search  Mandarin         Fashionistas
..                 ...           ...       ...                  ...
887           TechCorp         Email  Mandarin  Outdoor Adventurers
670           TechCorp    Influencer    French  Outdoor Adventurers
885           TechCorp  Social Media   English         Fashionistas
786           TechCorp       Display  Mandarin  Outdoor Adventurers
49            TechCorp  Social Media    German     Tech Enthusiasts

[625 rows x 4 columns]

In [6]:
df.query('Channel_Used == "YouTube"').sample(50)

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
196751,196752,Alpha Innovations,Display,Women 35-44,60 days,YouTube,0.09,"$13,597.00",7.22,New York,Mandarin,441,5815,6,Health & Wellness,2021-01-17
166672,166673,TechCorp,Email,Men 25-34,45 days,YouTube,0.06,"$17,819.00",3.45,Houston,French,653,2996,1,Outdoor Adventurers,2021-08-21
182383,182384,TechCorp,Influencer,All Ages,30 days,YouTube,0.04,"$7,132.00",4.90,Miami,Spanish,237,1301,4,Fashionistas,2021-09-06
31519,31520,DataTech Solutions,Social Media,Women 35-44,15 days,YouTube,0.03,"$8,978.00",6.91,New York,Mandarin,461,6966,10,Foodies,2021-05-10
120784,120785,Alpha Innovations,Email,Men 25-34,30 days,YouTube,0.03,"$16,313.00",3.05,Chicago,German,406,7850,5,Tech Enthusiasts,2021-12-01
9651,9652,DataTech Solutions,Display,Men 25-34,30 days,YouTube,0.05,"$14,044.00",6.89,Miami,English,961,6975,9,Outdoor Adventurers,2021-06-11
105976,105977,DataTech Solutions,Display,Men 18-24,60 days,YouTube,0.09,"$6,551.00",4.20,New York,Spanish,553,8422,1,Tech Enthusiasts,2021-05-07
155481,155482,NexGen Systems,Search,Men 18-24,15 days,YouTube,0.02,"$14,161.00",2.05,New York,Spanish,159,8433,1,Foodies,2021-12-23
61913,61914,DataTech Solutions,Display,Women 25-34,60 days,YouTube,0.05,"$19,035.00",5.99,Chicago,English,179,6570,8,Tech Enthusiasts,2021-08-17
45734,45735,Innovate Industries,Search,Women 35-44,30 days,YouTube,0.03,"$6,613.00",4.60,Miami,Mandarin,697,1920,1,Fashionistas,2021-04-20
160224,160225,TechCorp,Influencer,Men 25-34,60 days,YouTube,0.03,"$11,839.00",5.42,Los Angeles,French,886,4068,2,Health & Wellness,2021-12-21
19926,19927,TechCorp,Social Media,Men 18-24,60 days,YouTube,0.12,"$19,218.00",2.44,Chicago,French,960,8544,10,Tech Enthusiasts,2021-08-05
68084,68085,DataTech Solutions,Search,Men 25-34,15 days,YouTube,0.06,"$16,214.00",4.98,Chicago,Spanish,288,1115,3,Outdoor Adventurers,2021-07-14
150945,150946,DataTech Solutions,Social Media,Women 25-34,45 days,YouTube,0.07,"$16,946.00",3.76,Los Angeles,French,124,4143,3,Outdoor Adventurers,2021-07-20
101195,101196,NexGen Systems,Social Media,Men 18-24,30 days,YouTube,0.09,"$10,100.00",4.90,Miami,Spanish,162,2487,7,Health & Wellness,2021-04-01
68832,68833,DataTech Solutions,Search,Women 25-34,60 days,YouTube,0.13,"$9,689.00",5.86,Houston,French,677,5619,2,Fashionistas,2021-08-01
163048,163049,NexGen Systems,Social Media,Women 25-34,60 days,YouTube,0.15,"$17,593.00",7.05,Miami,English,269,2234,1,Fashionistas,2021-09-16
47517,47518,Innovate Industries,Social Media,Women 25-34,60 days,YouTube,0.05,"$8,202.00",4.57,Los Angeles,German,925,9693,8,Foodies,2021-03-09
114650,114651,Alpha Innovations,Display,Men 25-34,15 days,YouTube,0.10,"$10,986.00",2.27,Chicago,German,243,4450,7,Health & Wellness,2021-02-10
116673,116674,DataTech Solutions,Influencer,Women 25-34,30 days,YouTube,0.03,"$6,679.00",6.76,Houston,French,208,9926,7,Health & Wellness,2021-08-27
186673,186674,NexGen Systems,Influencer,Men 18-24,60 days,YouTube,0.09,"$17,632.00",5.74,Chicago,German,971,9311,6,Foodies,2021-06-08
154753,154754,TechCorp,Display,All Ages,60 days,YouTube,0.11,"$5,465.00",4.39,Miami,English,601,8514,6,Outdoor Adventurers,2021-12-25
104297,104298,Alpha Innovations,Influencer,Men 25-34,45 days,YouTube,0.14,"$13,891.00",7.13,Miami,French,408,8764,6,Tech Enthusiasts,2021-09-30
11478,11479,Alpha Innovations,Social Media,Women 35-44,15 days,YouTube,0.04,"$16,260.00",6.13,Los Angeles,French,377,5458,10,Fashionistas,2021-06-13
35666,35667,DataTech Solutions,Display,Women 25-34,45 days,YouTube,0.08,"$17,436.00",6.53,New York,Mandarin,608,9988,1,Foodies,2021-09-19
40569,40570,Innovate Industries,Influencer,Women 25-34,15 days,YouTube,0.06,"$18,626.00",3.29,Los Angeles,Mandarin,548,9714,9,Tech Enthusiasts,2021-02-24
187558,187559,NexGen Systems,Email,Women 25-34,15 days,YouTube,0.05,"$16,898.00",3.32,Miami,English,171,7761,6,Fashionistas,2021-11-10
13729,13730,NexGen Systems,Social Media,Men 18-24,15 days,YouTube,0.06,"$9,831.00",2.10,Miami,French,572,2301,10,Fashionistas,2021-08-13
138643,138644,DataTech Solutions,Email,All Ages,45 days,YouTube,0.05,"$17,202.00",4.50,Houston,English,797,8012,5,Outdoor Adventurers,2021-11-05
115867,115868,DataTech Solutions,Display,Women 25-34,45 days,YouTube,0.10,"$14,269.00",3.76,Chicago,French,878,4298,3,Outdoor Adventurers,2021-06-12
12607,12608,Innovate Industries,Email,Men 18-24,30 days,YouTube,0.14,"$13,075.00",7.05,Los Angeles,Spanish,195,9415,4,Outdoor Adventurers,2021-07-17
23418,23419,Alpha Innovations,Display,Men 25-34,45 days,YouTube,0.08,"$14,486.00",7.65,Los Angeles,German,343,5012,6,Outdoor Adventurers,2021-02-28
154936,154937,NexGen Systems,Email,Women 25-34,45 days,YouTube,0.03,"$5,480.00",6.49,New York,Spanish,124,9015,5,Health & Wellness,2021-06-26
137157,137158,TechCorp,Display,All Ages,30 days,YouTube,0.08,"$19,583.00",2.42,Houston,Spanish,113,4422,10,Foodies,2021-10-10
61018,61019,NexGen Systems,Social Media,Men 18-24,60 days,YouTube,0.02,"$19,842.00",3.62,Houston,French,968,6648,4,Fashionistas,2021-03-05
48645,48646,Innovate Industries,Influencer,Men 25-34,15 days,YouTube,0.07,"$15,117.00",5.28,Miami,English,705,7514,2,Outdoor Adventurers,2021-04-11
58728,58729,DataTech Solutions,Search,Men 25-34,30 days,YouTube,0.09,"$10,486.00",6.80,Chicago,English,597,3504,2,Health & Wellness,2021-11-25
22074,22075,Alpha Innovations,Search,All Ages,30 days,YouTube,0.03,"$17,815.00",3.75,Los Angeles,English,413,4836,9,Fashionistas,2021-06-24
22173,22174,NexGen Systems,Social Media,Women 25-34,45 days,YouTube,0.14,"$11,093.00",2.89,Miami,Mandarin,456,1615,10,Tech Enthusiasts,2021-10-01
90049,90050,Alpha Innovations,Email,Men 25-34,60 days,YouTube,0.09,"$6,236.00",4.81,Chicago,German,238,9204,6,Tech Enthusiasts,2021-09-17
107853,107854,DataTech Solutions,Social Media,Men 18-24,45 days,YouTube,0.02,"$11,164.00",3.76,Houston,Spanish,153,9037,9,Fashionistas,2021-06-28
21185,21186,DataTech Solutions,Social Media,Women 35-44,15 days,YouTube,0.10,"$7,504.00",6.16,Los Angeles,French,214,8409,9,Tech Enthusiasts,2021-01-16
86019,86020,NexGen Systems,Display,All Ages,60 days,YouTube,0.06,"$18,068.00",2.89,Los Angeles,English,127,1431,7,Foodies,2021-09-02
104836,104837,DataTech Solutions,Social Media,Women 25-34,15 days,YouTube,0.02,"$9,677.00",6.49,New York,French,903,7863,2,Tech Enthusiasts,2021-03-23
61327,61328,DataTech Solutions,Display,Men 25-34,60 days,YouTube,0.14,"$14,600.00",4.93,Chicago,German,494,6159,6,Tech Enthusiasts,2021-01-08
127710,127711,NexGen Systems,Influencer,Women 35-44,30 days,YouTube,0.10,"$7,387.00",6.80,Miami,English,267,4433,4,Tech Enthusiasts,2021-11-22
143384,143385,NexGen Systems,Email,Women 35-44,60 days,YouTube,0.09,"$12,411.00",6.29,Miami,French,710,9509,2,Foodies,2021-11-01
162354,162355,TechCorp,Display,Men 18-24,30 days,YouTube,0.08,"$14,966.00",7.63,New York,Spanish,795,5587,5,Outdoor Adventurers,2021-10-22
43397,43398,NexGen Systems,Influencer,Men 18-24,60 days,YouTube,0.13,"$10,777.00",7.88,Houston,French,262,7932,10,Tech Enthusiasts,2021-11-24
55637,55638,NexGen Systems,Search,Men 18-24,60 days,YouTube,0.14,"$17,465.00",3.18,Miami,Mandarin,453,8775,10,Fashionistas,2021-06-07

In [5]:
df.query('Channel_Used == "YouTube"').sample(50).to_csv('data\youtube_campaigns_sample.csv', index=False)

<>:1: SyntaxWarning: invalid escape sequence '\y'
<>:1: SyntaxWarning: invalid escape sequence '\y'
C:\Users\GIGABYTE\AppData\Local\Temp\ipykernel_25336\2558930118.py:1: SyntaxWarning: invalid escape sequence '\y'
  df.query('Channel_Used == "YouTube"').sample(50).to_csv('data\youtube_campaigns_sample.csv', index=False)

In [11]:
df.Language.unique()

<StringArray>
['Spanish', 'German', 'French', 'Mandarin', 'English']
Length: 5, dtype: str

In [8]:
from datetime import datetime, timedelta
def create_rango_fechas():
    anios = [2022, 2023, 2024]
    meses = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    range_dates = []
    for anio in anios:
        for mes in meses:
            inicio_dt = datetime(anio, mes, 1)
            inicio = f"{inicio_dt.month}/{inicio_dt.day}/{inicio_dt.year}"
            if mes == 12:
                final_dt = datetime(anio, mes, 31) - timedelta(days=1)
                final = f"{final_dt.month}/{final_dt.day}/{final_dt.year}"
            else:
                final_dt = datetime(anio, mes + 1, 1) - timedelta(days=1)
                final = f"{final_dt.month}/{final_dt.day}/{final_dt.year}"
            range_dates.append([inicio, final])
    return range_dates

rango_fechas = create_rango_fechas()[:-9]
for fecha in rango_fechas:
    print(fecha)

['1/1/2022', '1/31/2022']
['2/1/2022', '2/28/2022']
['3/1/2022', '3/31/2022']
['4/1/2022', '4/30/2022']
['5/1/2022', '5/31/2022']
['6/1/2022', '6/30/2022']
['7/1/2022', '7/31/2022']
['8/1/2022', '8/31/2022']
['9/1/2022', '9/30/2022']
['10/1/2022', '10/31/2022']
['11/1/2022', '11/30/2022']
['12/1/2022', '12/30/2022']
['1/1/2023', '1/31/2023']
['2/1/2023', '2/28/2023']
['3/1/2023', '3/31/2023']
['4/1/2023', '4/30/2023']
['5/1/2023', '5/31/2023']
['6/1/2023', '6/30/2023']
['7/1/2023', '7/31/2023']
['8/1/2023', '8/31/2023']
['9/1/2023', '9/30/2023']
['10/1/2023', '10/31/2023']
['11/1/2023', '11/30/2023']
['12/1/2023', '12/30/2023']
['1/1/2024', '1/31/2024']
['2/1/2024', '2/29/2024']
['3/1/2024', '3/31/2024']